# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdNwNNayGfEIMDcV_DxKcm-l0mWht0WZ
"""

import collections

def eliminate_left_recursion(grammar):
    """
    Eliminates immediate left recursion from the grammar.
    Productions are handled as lists of tokens.
    """
    new_grammar = collections.defaultdict(list)

    for non_terminal, productions in grammar.items():
        left_rec = []
        no_left_rec = []
        for prod in productions:
            if prod and prod[0] == non_terminal:
                left_rec.append(prod[1:])
            else:
                no_left_rec.append(prod)

        if left_rec:
            new_nt = non_terminal + "'"
            # A -> beta A'
            for beta in no_left_rec:
                if beta == ['!']:
                    new_grammar[non_terminal].append([new_nt])
                else:
                    new_grammar[non_terminal].append(beta + [new_nt])
            if not no_left_rec:
                new_grammar[non_terminal].append([new_nt])

            # A' -> alpha A' | !
            for alpha in left_rec:
                new_grammar[new_nt].append(alpha + [new_nt])
            new_grammar[new_nt].append(['!'])
        else:
            new_grammar[non_terminal] = productions

    return dict(new_grammar)

def eliminate_left_factoring(grammar):
    """
    Eliminates left factoring by finding common token prefixes among production rules.
    """
    current_grammar = {nt: list(prods) for nt, prods in grammar.items()}
    changed = True

    while changed:
        changed = False
        step_grammar = {}

        for nt, prods in current_grammar.items():
            if len(prods) <= 1:
                step_grammar[nt] = prods
                continue

            # Sort productions to easily find adjacent matches
            prods.sort()
            prefix = []

            for i in range(len(prods) - 1):
                p1, p2 = prods[i], prods[i+1]
                min_len = min(len(p1), len(p2))
                j = 0
                while j < min_len and p1[j] == p2[j] and p1[j] != '!':
                    j += 1
                if j > 0:
                    prefix = p1[:j]
                    break

            if prefix:
                changed = True
                new_nt = nt + '"'
                while new_nt in current_grammar or new_nt in step_grammar:
                    new_nt += '"'

                matched = [p for p in prods if p[:len(prefix)] == prefix]
                unmatched = [p for p in prods if p[:len(prefix)] != prefix]

                step_grammar[nt] = unmatched + [prefix + [new_nt]]

                new_prods = []
                for p in matched:
                    rem = p[len(prefix):]
                    new_prods.append(rem if rem else ["!"])
                step_grammar[new_nt] = new_prods
            else:
                step_grammar[nt] = prods

        current_grammar = step_grammar

    return current_grammar

def compute_first(grammar, non_terminals, terminals):
    first = {nt: set() for nt in non_terminals}

    def get_first_of_sequence(token_list):
        if not token_list or token_list == ['!']:
            return {'!'}

        res = set()
        for token in token_list:
            if token in terminals or token == '!':
                res.add(token)
                break
            elif token in non_terminals:
                token_first = first[token]
                res.update(token_first - {'!'})
                if '!' not in token_first:
                    break
        else:
            res.add('!')
        return res

    changed = True
    while changed:
        changed = False
        for nt, prods in grammar.items():
            for prod in prods:
                prod_first = get_first_of_sequence(prod)
                before_len = len(first[nt])
                first[nt].update(prod_first)
                if len(first[nt]) > before_len:
                    changed = True

    return first, get_first_of_sequence

def compute_follow(grammar, start_symbol, non_terminals, terminals, first_dict, get_first_seq):
    follow = {nt: set() for nt in non_terminals}
    follow[start_symbol].add('$')

    changed = True
    while changed:
        changed = False
        for nt, prods in grammar.items():
            for prod in prods:
                if prod == ['!']:
                    continue
                for i, token in enumerate(prod):
                    if token in non_terminals:
                        next_seq = prod[i+1:]
                        next_first = get_first_seq(next_seq)

                        before_len = len(follow[token])
                        follow[token].update(next_first - {'!'})

                        if '!' in next_first:
                            follow[token].update(follow[nt])

                        if len(follow[token]) > before_len:
                            changed = True
    return follow

def create_ll1_table(grammar, first_dict, follow_dict, get_first_seq, non_terminals, terminals):
    all_terminals = sorted(list(terminals - {'!'})) + ['$']
    table = {nt: {t: None for t in all_terminals} for nt in non_terminals}
    is_ll1 = True

    for nt, prods in grammar.items():
        for prod in prods:
            prod_first = get_first_seq(prod)
            prod_str = "".join(prod)

            for t in prod_first - {'!'}:
                if table[nt][t] is not None:
                    print(f"\n[Conflict] Shift-Reduce / Reduce-Reduce Conflict at [{nt}, {t}]: Matches both '{''.join(table[nt][t])}' and '{prod_str}'")
                    is_ll1 = False
                table[nt][t] = prod

            if '!' in prod_first:
                for t in follow_dict[nt]:
                    if table[nt][t] is not None:
                        print(f"\n[Conflict] Shift-Reduce / Reduce-Reduce Conflict at [{nt}, {t}]: Matches both '{''.join(table[nt][t])}' and '{prod_str}'")
                        is_ll1 = False
                    table[nt][t] = prod

    return table, all_terminals, is_ll1

def main():
    print("--- LL(1) Parser Engine ---")
    try:
        num_productions = int(input("Enter number of production rules: "))
    except ValueError:
        print("Invalid number.")
        return

    print("Enter rules in the format 'A->B' or 'A->B|C' (use '!' for Epsilon):")
    raw_grammar = collections.defaultdict(list)
    start_symbol = None

    for i in range(num_productions):
        rule = input(f"Rule {i+1}: ").strip()
        if "->" not in rule:
            print("Invalid format. Missing '->'")
            return
        lhs, rhs = rule.split("->")
        lhs = lhs.strip()
        if not start_symbol:
            start_symbol = lhs

        alternatives = [alt.strip() for alt in rhs.split("|")]
        for alt in alternatives:
            # Tokenize initial raw input cleanly character by character
            token_list = [char for char in alt] if alt != '!' else ['!']
            raw_grammar[lhs].append(token_list)

    print("\nProcessing Grammar Transformations...")
    no_rec_grammar = eliminate_left_recursion(raw_grammar)
    final_grammar = eliminate_left_factoring(no_rec_grammar)

    non_terminals = list(final_grammar.keys())
    terminals = set()
    for prods in final_grammar.values():
        for prod in prods:
            for token in prod:
                if token not in non_terminals and token != '!':
                    terminals.add(token)

    print("\n--- Transformed Grammar ---")
    for nt, prods in final_grammar.items():
        print(f"{nt} -> {' | '.join([''.join(p) for p in prods])}")

    first_sets, get_first_seq = compute_first(final_grammar, non_terminals, terminals)
    follow_sets = compute_follow(final_grammar, start_symbol, non_terminals, terminals, first_sets, get_first_seq)

    print("\n--- FIRST Sets ---")
    for nt in non_terminals:
        print(f"FIRST({nt}) = {{ {', '.join(sorted(first_sets[nt]))} }}")

    print("\n--- FOLLOW Sets ---")
    for nt in non_terminals:
        print(f"FOLLOW({nt}) = {{ {', '.join(sorted(follow_sets[nt]))} }}")

    table, columns, is_ll1 = create_ll1_table(final_grammar, first_sets, follow_sets, get_first_seq, non_terminals, terminals)

    print("\n--- LL(1) Parsing Table ---")
    header = "\t".join(columns)
    print(f"NT\t{header}")
    print("-" * (8 * (len(columns) + 1)))

    for nt in non_terminals:
        row_str = f"{nt}\t"
        for col in columns:
            val = table[nt][col]
            row_str += f"{''.join(val) if val else '_'}\t"
        print(row_str)

if __name__ == "__main__":
    main()